// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zqr233qr/story-trim/internal/config"
	"github.com/zqr233qr/story-trim/internal/handler"
	"github.com/zqr233qr/story-trim/internal/repository"
	"github.com/zqr233qr/story-trim/internal/service"
	"github.com/zqr233qr/story-trim/internal/storage"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAPIComponents(db *gorm.DB, jwtSecret string, llm *config.LLM, store storage.Storage) (*APIComponents, error) {
	authRepository := repository.NewAuthRepository(db)
	bookRepository := repository.NewBookRepository(db, store)
	taskRepository := repository.NewTaskRepository(db)
	taskItemRepository := repository.NewTaskItemRepository(db)
	pointsRepository := repository.NewPointsRepository(db)
	contentRepository := repository.NewContentRepository(db)
	pointsService := service.NewPointsService(pointsRepository)
	authService := service.NewAuthService(authRepository, pointsService, jwtSecret)
	authHandler := handler.NewAuthHandler(authService)
	bookService := service.NewBookService(bookRepository, taskRepository)
	bookHandler := handler.NewBookHandler(bookService)
	llmService := service.NewLlmService(llm)
	trimService := service.NewTrimService(bookRepository, pointsService, llmService)
	trimHandler := handler.NewTrimHandler(trimService)
	taskService := provideTaskService(taskRepository, taskItemRepository, bookRepository, trimService, pointsService)
	taskHandler := handler.NewTaskHandler(taskService)
	chapterTrimHandler := handler.NewChapterTrimHandler(taskService)
	contentService := service.NewContentService(contentRepository)
	contentHandler := handler.NewContentHandler(contentService)
	pointsHandler := handler.NewPointsHandler(pointsService)
	apiComponents := NewAPIComponents(authHandler, bookHandler, trimHandler, taskHandler, chapterTrimHandler, contentHandler, pointsHandler, authService, taskService)
	return apiComponents, nil
}

// wire.go:

type APIComponents struct {
	AuthHandler        *handler.AuthHandler
	BookHandler        *handler.BookHandler
	TrimHandler        *handler.TrimHandler
	TaskHandler        *handler.TaskHandler
	ChapterTrimHandler *handler.ChapterTrimHandler
	ContentHandler     *handler.ContentHandler
	PointsHandler      *handler.PointsHandler
	AuthService        service.AuthServiceInterface
	TaskService        service.TaskServiceInterface
}

func NewAPIComponents(
	authHandler *handler.AuthHandler,
	bookHandler *handler.BookHandler,
	trimHandler *handler.TrimHandler,
	taskHandler *handler.TaskHandler,
	chapterTrimHandler *handler.ChapterTrimHandler,
	contentHandler *handler.ContentHandler,
	pointsHandler *handler.PointsHandler,
	authService service.AuthServiceInterface,
	taskService service.TaskServiceInterface,
) *APIComponents {
	return &APIComponents{
		AuthHandler:        authHandler,
		BookHandler:        bookHandler,
		TrimHandler:        trimHandler,
		TaskHandler:        taskHandler,
		ChapterTrimHandler: chapterTrimHandler,
		ContentHandler:     contentHandler,
		PointsHandler:      pointsHandler,
		AuthService:        authService,
		TaskService:        taskService,
	}
}

// Helper to provide the constant maxWorkers for TaskService
func provideTaskService(
	repo repository.TaskRepositoryInterface,
	taskItemRepo repository.TaskItemRepositoryInterface,
	bookRepo repository.BookRepositoryInterface,
	trimService service.TrimServiceInterface,
	pointsService service.PointsServiceInterface,
) *service.TaskService {
	return service.NewTaskService(repo, taskItemRepo, bookRepo, trimService, pointsService, 4)
}
