// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zqr233qr/story-trim/internal/config"
	"github.com/zqr233qr/story-trim/internal/handler"
	"github.com/zqr233qr/story-trim/internal/repository"
	"github.com/zqr233qr/story-trim/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAPIComponents(db *gorm.DB, jwtSecret string, llm *config.LLM) (*APIComponents, error) {
	authRepository := repository.NewAuthRepository(db)
	authService := service.NewAuthService(authRepository, jwtSecret)
	authHandler := handler.NewAuthHandler(authService)
	bookRepository := repository.NewBookRepository(db)
	bookService := service.NewBookService(bookRepository)
	bookHandler := handler.NewBookHandler(bookService)
	llmService := service.NewLlmService(llm)
	trimService := service.NewTrimService(bookRepository, llmService)
	trimHandler := handler.NewTrimHandler(trimService)
	taskRepository := repository.NewTaskRepository(db)
	taskService := provideTaskService(taskRepository, bookRepository, trimService)
	taskHandler := handler.NewTaskHandler(taskService)
	apiComponents := NewAPIComponents(authHandler, bookHandler, trimHandler, taskHandler, authService)
	return apiComponents, nil
}

// wire.go:

type APIComponents struct {
	AuthHandler *handler.AuthHandler
	BookHandler *handler.BookHandler
	TrimHandler *handler.TrimHandler
	TaskHandler *handler.TaskHandler
	AuthService service.AuthServiceInterface
}

func NewAPIComponents(
	authHandler *handler.AuthHandler,
	bookHandler *handler.BookHandler,
	trimHandler *handler.TrimHandler,
	taskHandler *handler.TaskHandler,
	authService service.AuthServiceInterface,
) *APIComponents {
	return &APIComponents{
		AuthHandler: authHandler,
		BookHandler: bookHandler,
		TrimHandler: trimHandler,
		TaskHandler: taskHandler,
		AuthService: authService,
	}
}

// Helper to provide the constant maxWorkers for TaskService
func provideTaskService(
	repo repository.TaskRepositoryInterface,
	bookRepo repository.BookRepositoryInterface,
	trimService service.TrimServiceInterface,
) *service.TaskService {
	return service.NewTaskService(repo, bookRepo, trimService, 4)
}
