// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zqr233qr/story-trim/internal/config"
	"github.com/zqr233qr/story-trim/internal/handler"
	"github.com/zqr233qr/story-trim/internal/repository"
	"github.com/zqr233qr/story-trim/internal/service"
	"github.com/zqr233qr/story-trim/internal/storage"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAPIComponents(db *gorm.DB, jwtSecret string, llm *config.LLM, store storage.Storage) (*APIComponents, error) {
	authRepository := repository.NewAuthRepository(db)
	authService := service.NewAuthService(authRepository, jwtSecret)
	authHandler := handler.NewAuthHandler(authService)
	bookRepository := repository.NewBookRepository(db, store)
	taskRepository := repository.NewTaskRepository(db)
	bookService := service.NewBookService(bookRepository, taskRepository)
	bookHandler := handler.NewBookHandler(bookService)
	llmService := service.NewLlmService(llm)
	trimService := service.NewTrimService(bookRepository, llmService)
	trimHandler := handler.NewTrimHandler(trimService)
	taskService := provideTaskService(taskRepository, bookRepository, trimService)
	taskHandler := handler.NewTaskHandler(taskService)
	contentRepository := repository.NewContentRepository(db)
	contentService := service.NewContentService(contentRepository)
	contentHandler := handler.NewContentHandler(contentService)
	apiComponents := NewAPIComponents(authHandler, bookHandler, trimHandler, taskHandler, contentHandler, authService, taskService)
	return apiComponents, nil
}

// wire.go:

type APIComponents struct {
	AuthHandler    *handler.AuthHandler
	BookHandler    *handler.BookHandler
	TrimHandler    *handler.TrimHandler
	TaskHandler    *handler.TaskHandler
	ContentHandler *handler.ContentHandler
	AuthService    service.AuthServiceInterface
	TaskService    service.TaskServiceInterface
}

func NewAPIComponents(
	authHandler *handler.AuthHandler,
	bookHandler *handler.BookHandler,
	trimHandler *handler.TrimHandler,
	taskHandler *handler.TaskHandler,
	contentHandler *handler.ContentHandler,
	authService service.AuthServiceInterface,
	taskService service.TaskServiceInterface,
) *APIComponents {
	return &APIComponents{
		AuthHandler:    authHandler,
		BookHandler:    bookHandler,
		TrimHandler:    trimHandler,
		TaskHandler:    taskHandler,
		ContentHandler: contentHandler,
		AuthService:    authService,
		TaskService:    taskService,
	}
}

// Helper to provide the constant maxWorkers for TaskService
func provideTaskService(
	repo repository.TaskRepositoryInterface,
	bookRepo repository.BookRepositoryInterface,
	trimService service.TrimServiceInterface,
) *service.TaskService {
	return service.NewTaskService(repo, bookRepo, trimService, 4)
}
